---
 - hosts: ansible_hosts
   gather_facts: true
   become: true
   vars:
     package: "nginx"
   tasks:
     - name: update cache
       apt:
         update_cache: yes
     - name: Install "nginx"
       apt:
         name: "{{package}}" 
     - name: Nginx version
       shell: >
         nginx -v
       register: nginx_version

     - name: Print nginx version
       debug:
         msg: "{{nginx_version}}"
        
